### PR TITLE
fix scan timeout in driver

### PR DESCRIPTION
**Pull request by fariouche**
The timeout is too short, so it is interfering with scan, even if the scan found results.
Removed the timeout, as it seems not necessary (it is up to the userland to setup the timeout, not the driver)

### CODE REVIEW

**Comment by kimocoder** [comment]
Fantastic! Great work, again.

**Comment by ZerBea** [comment]
I just want to let you know that hcxdumptool is working fine with this driver:

[35053.423872] usb 5-4.5: Product: Edimax AC600 USB
[35053.423874] usb 5-4.5: Manufacturer: Realtek

[18:48:32 - 001] xxxxxxxxxxxx -> f0a2259b9825 [FOUND PMKID CLIENT-LESS]

**Comment by kimocoder** [comment]
That's great. The attack was just added to wifite2, so I'll check ut out soon. Thanks for info

**Comment by kimocoder** [comment]
@ZerBea this is the development repo for the main repo, https://github.com/aircrack-ng/rtl8812au -- we're doing the tests here before pushing it to the main. Just do you noe, you might star the other one instead. Thanks

**Pull request merged**
